# Generated by Django 2.0 on 2019-02-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190215_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rend_num',
            field=models.IntegerField(default=0),
        ),
    ]
