# Generated by Django 2.0 on 2019-02-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_rend_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rend_num',
            field=models.IntegerField(default=1),
        ),
    ]
