# Generated by Django 2.0 on 2019-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190215_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rend_num',
            field=models.IntegerField(default=0),
        ),
    ]
